/* ============================================================
   DATA LAYER — single source of truth for the whole site.
   Add a store/coupon/category/article by adding an object here.
   Nothing in the UI hard-codes content; everything reads this file.
   ============================================================ */

const CATEGORIES = [
  { id: "fashion",    slug: "fashion",    icon: "shirt",
    name: { ar: "أزياء",        en: "Fashion" },
    desc: { ar: "أحدث أكواد الخصم على الملابس والأحذية والإكسسوارات من أشهر الماركات العالمية والمحلية.",
            en: "The latest discount codes on clothing, shoes and accessories from top global and local brands." } },
  { id: "electronics", slug: "electronics", icon: "cpu",
    name: { ar: "إلكترونيات", en: "Electronics" },
    desc: { ar: "وفر على الهواتف والحواسيب والأجهزة المنزلية الذكية مع عروض محدثة يوميًا.",
            en: "Save on phones, laptops and smart home devices with deals updated daily." } },
  { id: "travel",      slug: "travel",      icon: "plane",
    name: { ar: "سفر",         en: "Travel" },
    desc: { ar: "أكواد خصم على حجوزات الطيران والفنادق وتأجير السيارات لرحلتك القادمة.",
            en: "Discount codes for flights, hotels and car rentals for your next trip." } },
  { id: "beauty",      slug: "beauty",      icon: "sparkles",
    name: { ar: "تجميل",       en: "Beauty" },
    desc: { ar: "عروض على منتجات العناية بالبشرة والمكياج والعطور من أفضل الماركات.",
            en: "Deals on skincare, makeup and fragrances from the best beauty brands." } },
  { id: "health",      slug: "health",      icon: "heart",
    name: { ar: "صحة",         en: "Health" },
    desc: { ar: "خصومات على المكملات الغذائية والمنتجات الصحية والعافية.",
            en: "Discounts on supplements and health & wellness products." } },
  { id: "home",        slug: "home",        icon: "home",
    name: { ar: "منزل",        en: "Home" },
    desc: { ar: "وفر على الأثاث وأدوات المنزل والديكور مع أحدث العروض.",
            en: "Save on furniture, home goods and decor with the latest offers." } },
  { id: "food",        slug: "food",        icon: "utensils",
    name: { ar: "مطاعم",       en: "Food" },
    desc: { ar: "أكواد خصم على طلبات المطاعم وتوصيل الطعام.",
            en: "Discount codes for restaurant orders and food delivery." } },
  { id: "sports",      slug: "sports",      icon: "dumbbell",
    name: { ar: "رياضة",       en: "Sports" },
    desc: { ar: "عروض على المعدات الرياضية والملابس الرياضية والاشتراكات.",
            en: "Offers on sports gear, athletic wear and fitness memberships." } },
  { id: "kids",        slug: "kids",        icon: "baby",
    name: { ar: "أطفال",       en: "Kids" },
    desc: { ar: "خصومات على ملابس الأطفال والألعاب ومستلزمات الرضع.",
            en: "Discounts on kids' clothing, toys and baby essentials." } },
  { id: "apps",        slug: "apps",        icon: "smartphone",
    name: { ar: "تطبيقات",     en: "Apps" },
    desc: { ar: "أكواد خصم للاشتراكات في التطبيقات والخدمات الرقمية.",
            en: "Discount codes for app subscriptions and digital services." } },
  { id: "digital-services", slug: "digital-services", icon: "cloud",
    name: { ar: "خدمات رقمية", en: "Digital Services" },
    desc: { ar: "عروض على الاستضافة والبرمجيات والأدوات الرقمية.",
            en: "Deals on hosting, software and digital tools." } },
];

const STORES = [
  { id: "iherb", slug: "iherb", category: "health", featured: true,
    name: "iHerb", website: "https://www.iherb.com",
    logo: "https://logo.clearbit.com/iherb.com",
    desc: { ar: "متجر iHerb الأمريكي الرائد لبيع المكملات الغذائية والمنتجات الطبيعية والعضوية بشحن سريع لجميع أنحاء العالم.",
            en: "iHerb is a leading US retailer of supplements, natural and organic products with fast worldwide shipping." } },
  { id: "namshi", slug: "namshi", category: "fashion", featured: true,
    name: "Namshi", website: "https://www.namshi.com",
    logo: "https://logo.clearbit.com/namshi.com",
    desc: { ar: "نمشي هي وجهتك الأولى للأزياء والأحذية والإكسسوارات في الشرق الأوسط، تضم آلاف الماركات العالمية والمحلية.",
            en: "Namshi is the leading fashion destination in the Middle East, featuring thousands of global and local brands." } },
  { id: "noon", slug: "noon", category: "electronics", featured: true,
    name: "Noon", website: "https://www.noon.com",
    logo: "https://logo.clearbit.com/noon.com",
    desc: { ar: "نون هي المنصة الرقمية الأكبر في المنطقة لبيع الإلكترونيات والأجهزة المنزلية ومنتجات متنوعة.",
            en: "Noon is the region's largest online marketplace for electronics, home appliances and more." } },
  { id: "booking", slug: "booking", category: "travel", featured: true,
    name: "Booking.com", website: "https://www.booking.com",
    logo: "https://logo.clearbit.com/booking.com",
    desc: { ar: "بوكينج دوت كوم منصة عالمية لحجز الفنادق والشقق والمنتجعات في أكثر من 220 دولة.",
            en: "Booking.com is a global platform for booking hotels, apartments and resorts in over 220 countries." } },
  { id: "sephora", slug: "sephora", category: "beauty", featured: true,
    name: "Sephora", website: "https://www.sephora.com",
    logo: "https://logo.clearbit.com/sephora.com",
    desc: { ar: "سيفورا هي الوجهة العالمية الأولى لمنتجات التجميل والعناية بالبشرة والعطور الفاخرة.",
            en: "Sephora is the world's leading destination for beauty, skincare and prestige fragrance." } },
  { id: "ikea", slug: "ikea", category: "home", featured: false,
    name: "IKEA", website: "https://www.ikea.com",
    logo: "https://logo.clearbit.com/ikea.com",
    desc: { ar: "إيكيا العلامة السويدية الشهيرة لأثاث ومستلزمات المنزل بتصميم عملي وأسعار معقولة.",
            en: "IKEA is the renowned Swedish brand for functional, affordable home furniture and goods." } },
  { id: "talabat", slug: "talabat", category: "food", featured: false,
    name: "Talabat", website: "https://www.talabat.com",
    logo: "https://logo.clearbit.com/talabat.com",
    desc: { ar: "طلبات هو تطبيق توصيل الطعام الأشهر في الشرق الأوسط يضم آلاف المطاعم.",
            en: "Talabat is the leading food delivery app in the Middle East with thousands of restaurants." } },
  { id: "adidas", slug: "adidas", category: "sports", featured: false,
    name: "Adidas", website: "https://www.adidas.com",
    logo: "https://logo.clearbit.com/adidas.com",
    desc: { ar: "أديداس العلامة الرياضية العالمية الرائدة في الأحذية والملابس الرياضية.",
            en: "Adidas is a leading global sportswear brand for footwear and athletic apparel." } },
  { id: "mumzworld", slug: "mumzworld", category: "kids", featured: false,
    name: "Mumzworld", website: "https://www.mumzworld.com",
    logo: "https://logo.clearbit.com/mumzworld.com",
    desc: { ar: "مامز وورلد المتجر الأول لمستلزمات الأطفال والرضع في المنطقة العربية.",
            en: "Mumzworld is the region's top destination for baby and kids' essentials." } },
  { id: "netflix", slug: "netflix", category: "apps", featured: false,
    name: "Netflix", website: "https://www.netflix.com",
    logo: "https://logo.clearbit.com/netflix.com",
    desc: { ar: "نتفليكس منصة البث الأشهر عالميًا للأفلام والمسلسلات.",
            en: "Netflix is the world's leading streaming platform for movies and shows." } },
  { id: "namecheap", slug: "namecheap", category: "digital-services", featured: false,
    name: "Namecheap", website: "https://www.namecheap.com",
    logo: "https://logo.clearbit.com/namecheap.com",
    desc: { ar: "نيمتشيب مزود عالمي لتسجيل النطاقات واستضافة المواقع بأسعار تنافسية.",
            en: "Namecheap is a global provider of domain registration and web hosting at competitive prices." } },
  { id: "sivvi", slug: "sivvi", category: "fashion", featured: false,
    name: "SIVVI", website: "https://www.sivvi.com",
    logo: "https://logo.clearbit.com/sivvi.com",
    desc: { ar: "سيفي متجر أزياء إلكتروني يقدم أحدث صيحات الموضة للرجال والنساء.",
            en: "SIVVI is an online fashion retailer offering the latest trends for men and women." } },
];

// Helper to compute an ISO date N days from "today" (site's reference date)
const REF_DATE = new Date("2026-08-25T00:00:00Z");
function daysFromRef(n) {
  const d = new Date(REF_DATE);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

const COUPONS = [
  { id: "c1", store: "iherb", slug: "iherb-20-off-first-order",
    code: "DGK0899", type: "code", discount: "20%",
    title: { ar: "خصم 20% على أول طلب", en: "20% off your first order" },
    desc: { ar: "احصل على خصم 20% على طلبك الأول من موقع iHerb، يشمل جميع الفئات تقريبًا.",
            en: "Get 20% off your first order at iHerb, covering nearly all categories." },
    terms: { ar: "صالح للعملاء الجدد فقط. لا يمكن دمجه مع عروض أخرى. الحد الأقصى للخصم 20 دولارًا.",
             en: "Valid for new customers only. Cannot be combined with other offers. Max discount $20." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(14),
    affiliateUrl: "https://www.iherb.com/?rcode=DGK0899",
    storeUrl: "https://www.iherb.com" },
  { id: "c2", store: "iherb", slug: "iherb-free-shipping",
    code: "", type: "deal", discount: "شحن مجاني",
    title: { ar: "شحن مجاني للطلبات فوق 60 دولارًا", en: "Free shipping on orders over $60" },
    desc: { ar: "لا حاجة لكود، يتم تفعيل الشحن المجاني تلقائيًا عند تجاوز قيمة السلة 60 دولارًا.",
            en: "No code needed — free shipping applies automatically on carts over $60." },
    terms: { ar: "يسري على الطلبات داخل دول مختارة فقط.",
             en: "Applies to select countries only." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(30),
    affiliateUrl: "https://www.iherb.com/?rcode=DGK0899",
    storeUrl: "https://www.iherb.com" },
  { id: "c3", store: "namshi", slug: "namshi-30-off-fashion",
    code: "NAM30", type: "code", discount: "30%",
    title: { ar: "خصم 30% على الأزياء المختارة", en: "30% off selected fashion" },
    desc: { ar: "وفر 30% على تشكيلة واسعة من الملابس والأحذية لدى نمشي.",
            en: "Save 30% on a wide selection of clothing and shoes at Namshi." },
    terms: { ar: "يستثني بعض الماركات الفاخرة. صالح لفترة محدودة.",
             en: "Excludes select premium brands. Limited time only." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(5),
    affiliateUrl: "https://www.namshi.com/promo/NAM30",
    storeUrl: "https://www.namshi.com" },
  { id: "c4", store: "namshi", slug: "namshi-end-of-season-sale",
    code: "", type: "deal", discount: "حتى 70%",
    title: { ar: "تخفيضات نهاية الموسم حتى 70%", en: "End of season sale up to 70%" },
    desc: { ar: "تخفيضات كبيرة على آلاف المنتجات مع نهاية الموسم.",
            en: "Massive discounts on thousands of products for end of season." },
    terms: { ar: "الأسعار كما هي معروضة على الموقع، لا حاجة لكود.",
             en: "Prices as shown on site, no code required." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(10),
    affiliateUrl: "https://www.namshi.com/sale",
    storeUrl: "https://www.namshi.com" },
  { id: "c5", store: "noon", slug: "noon-electronics-15-off",
    code: "NOONTECH15", type: "code", discount: "15%",
    title: { ar: "خصم 15% على الإلكترونيات", en: "15% off electronics" },
    desc: { ar: "خصم فوري 15% عند شراء أجهزة إلكترونية مختارة من نون.",
            en: "Instant 15% off on select electronics at Noon." },
    terms: { ar: "الحد الأقصى للخصم 100 ريال. يستثني بعض الماركات.",
             en: "Max discount 100 SAR. Excludes some brands." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(7),
    affiliateUrl: "https://www.noon.com/promo/NOONTECH15",
    storeUrl: "https://www.noon.com" },
  { id: "c6", store: "noon", slug: "noon-cashback-5",
    code: "", type: "cashback", discount: "5% Cashback",
    title: { ar: "استرداد نقدي 5% على جميع المشتريات", en: "5% cashback on all purchases" },
    desc: { ar: "احصل على استرداد نقدي 5% تلقائيًا عند الدفع عبر نون باي.",
            en: "Automatically earn 5% cashback when paying with noon pay." },
    terms: { ar: "يُضاف الرصيد خلال 3 أيام عمل.",
             en: "Balance credited within 3 business days." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(45),
    affiliateUrl: "https://www.noon.com",
    storeUrl: "https://www.noon.com" },
  { id: "c7", store: "booking", slug: "booking-10-off-hotels",
    code: "STAY10", type: "code", discount: "10%",
    title: { ar: "خصم 10% على حجوزات الفنادق", en: "10% off hotel bookings" },
    desc: { ar: "وفر 10% إضافية عند حجز فندقك القادم عبر Booking.com.",
            en: "Save an extra 10% when booking your next hotel via Booking.com." },
    terms: { ar: "يسري على فنادق مشاركة فقط. لا يشمل الإلغاء المجاني في كل الحالات.",
             en: "Applies to participating hotels only. Free cancellation not guaranteed in all cases." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(20),
    affiliateUrl: "https://www.booking.com/promo/STAY10",
    storeUrl: "https://www.booking.com" },
  { id: "c8", store: "sephora", slug: "sephora-free-gift",
    code: "GLOW25", type: "code", discount: "هدية مجانية",
    title: { ar: "هدية مجانية عند الشراء بقيمة 50 دولارًا", en: "Free gift with $50 purchase" },
    desc: { ar: "احصل على مجموعة عينات فاخرة مجانًا عند إنفاق 50 دولارًا أو أكثر.",
            en: "Get a free luxury sample set when you spend $50 or more." },
    terms: { ar: "حتى نفاد الكمية. هدية واحدة لكل عميل.",
             en: "While supplies last. One gift per customer." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(12),
    affiliateUrl: "https://www.sephora.com/promo/GLOW25",
    storeUrl: "https://www.sephora.com" },
  { id: "c9", store: "ikea", slug: "ikea-family-discount",
    code: "IKEAFAM", type: "code", discount: "15%",
    title: { ar: "خصم 15% لأعضاء IKEA Family", en: "15% off for IKEA Family members" },
    desc: { ar: "خصم حصري لأعضاء برنامج IKEA Family على تشكيلة واسعة من الأثاث.",
            en: "Exclusive discount for IKEA Family members on a wide furniture range." },
    terms: { ar: "يتطلب التسجيل في برنامج IKEA Family مسبقًا.",
             en: "Requires prior IKEA Family membership registration." },
    verified: false, active: true, featured: false,
    expirationDate: daysFromRef(25),
    affiliateUrl: "https://www.ikea.com/promo/IKEAFAM",
    storeUrl: "https://www.ikea.com" },
  { id: "c10", store: "talabat", slug: "talabat-50-off-first-order",
    code: "TALAB50", type: "code", discount: "50%",
    title: { ar: "خصم 50% على أول طلب", en: "50% off your first order" },
    desc: { ar: "خصم كبير 50% لأول طلب طعام عبر تطبيق طلبات.",
            en: "A big 50% discount on your first food order via the Talabat app." },
    terms: { ar: "الحد الأقصى للخصم 15 ريالًا. للعملاء الجدد فقط.",
             en: "Max discount 15 SAR. New customers only." },
    verified: true, active: true, featured: true,
    expirationDate: daysFromRef(3),
    affiliateUrl: "https://www.talabat.com/promo/TALAB50",
    storeUrl: "https://www.talabat.com" },
  { id: "c11", store: "adidas", slug: "adidas-25-off-sportswear",
    code: "RUN25", type: "code", discount: "25%",
    title: { ar: "خصم 25% على الملابس الرياضية", en: "25% off sportswear" },
    desc: { ar: "وفر 25% على مجموعة مختارة من الأحذية والملابس الرياضية من أديداس.",
            en: "Save 25% on a select range of shoes and sportswear from Adidas." },
    terms: { ar: "يستثني إصدارات محدودة ومنتجات التعاون الخاصة.",
             en: "Excludes limited editions and special collaborations." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(18),
    affiliateUrl: "https://www.adidas.com/promo/RUN25",
    storeUrl: "https://www.adidas.com" },
  { id: "c12", store: "mumzworld", slug: "mumzworld-baby-essentials-20",
    code: "BABY20", type: "code", discount: "20%",
    title: { ar: "خصم 20% على مستلزمات الأطفال", en: "20% off baby essentials" },
    desc: { ar: "خصم 20% على الحفاضات ومستلزمات العناية بالرضع من مامز وورلد.",
            en: "20% off diapers and baby care essentials at Mumzworld." },
    terms: { ar: "لا يشمل أجهزة الرضاعة والعربات.",
             en: "Excludes feeding devices and strollers." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(9),
    affiliateUrl: "https://www.mumzworld.com/promo/BABY20",
    storeUrl: "https://www.mumzworld.com" },
  { id: "c13", store: "netflix", slug: "netflix-one-month-free",
    code: "", type: "deal", discount: "شهر مجاني",
    title: { ar: "شهر مجاني للمشتركين الجدد", en: "One month free for new subscribers" },
    desc: { ar: "جرّب نتفليكس مجانًا لمدة شهر كامل عند التسجيل كمشترك جديد.",
            en: "Try Netflix free for a full month as a new subscriber." },
    terms: { ar: "العرض متاح في دول مختارة فقط ولمرة واحدة لكل حساب.",
             en: "Offer available in select countries only, once per account." },
    verified: false, active: true, featured: false,
    expirationDate: daysFromRef(60),
    affiliateUrl: "https://www.netflix.com",
    storeUrl: "https://www.netflix.com" },
  { id: "c14", store: "namecheap", slug: "namecheap-domain-first-year",
    code: "DOMAIN99", type: "code", discount: "$0.99",
    title: { ar: "تسجيل نطاق .com بـ 0.99 دولار للسنة الأولى", en: ".com domain for $0.99 first year" },
    desc: { ar: "سجّل نطاقك الجديد بسعر مخفض جدًا للسنة الأولى فقط.",
            en: "Register your new domain at a heavily discounted rate for the first year." },
    terms: { ar: "يتجدد بالسعر العادي بعد السنة الأولى.",
             en: "Renews at regular price after the first year." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(40),
    affiliateUrl: "https://www.namecheap.com/promo/DOMAIN99",
    storeUrl: "https://www.namecheap.com" },
  { id: "c15", store: "sivvi", slug: "sivvi-new-arrivals-20",
    code: "NEW20", type: "code", discount: "20%",
    title: { ar: "خصم 20% على أحدث الوصولات", en: "20% off new arrivals" },
    desc: { ar: "خصم فوري على أحدث تشكيلات الموضة من ماركاتك المفضلة.",
            en: "Instant discount on the latest fashion arrivals from your favorite brands." },
    terms: { ar: "غير قابل للدمج مع كوبونات أخرى.",
             en: "Not combinable with other coupons." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(2),
    affiliateUrl: "https://www.sivvi.com/promo/NEW20",
    storeUrl: "https://www.sivvi.com" },
  { id: "c16", store: "iherb", slug: "iherb-vitamins-buy-more-save-more",
    code: "SAVEMORE", type: "code", discount: "حتى 25%",
    title: { ar: "اشترِ أكثر ووفر أكثر على الفيتامينات", en: "Buy more, save more on vitamins" },
    desc: { ar: "كلما زادت مشترياتك من الفيتامينات، زاد الخصم حتى نسبة 25%.",
            en: "The more vitamins you buy, the more you save — up to 25% off." },
    terms: { ar: "يحتسب الخصم تلقائيًا في السلة حسب الكمية.",
             en: "Discount is calculated automatically at checkout based on quantity." },
    verified: true, active: true, featured: false,
    expirationDate: daysFromRef(15),
    affiliateUrl: "https://www.iherb.com/?rcode=DGK0899",
    storeUrl: "https://www.iherb.com" },
];

const BLOG_POSTS = [
  { id: "b1", slug: "how-to-save-money-online-shopping",
    category: "fashion", author: "فريق التحرير", authorEn: "Editorial Team",
    date: "2026-08-18", readingTime: { ar: "5 دقائق", en: "5 min read" },
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
    title: { ar: "10 طرق ذكية لتوفير المال عند التسوق أونلاين",
             en: "10 Smart Ways to Save Money Shopping Online" },
    excerpt: { ar: "تعرف على أفضل الاستراتيجيات العملية لتقليل فاتورة تسوقك الإلكتروني دون التضحية بما تريد شراءه.",
               en: "Discover practical strategies to cut your online shopping bill without giving up what you want to buy." },
    relatedStores: ["namshi", "noon"], relatedCoupons: ["c3", "c5"],
    content: {
      ar: [
        { h: "ابدأ دائمًا بالبحث عن كود خصم" },
        { p: "قبل إتمام أي عملية شراء، خذ دقيقة للبحث عن كود خصم صالح للمتجر الذي تتسوق منه. غالبًا ما توفر هذه الأكواد نسبة خصم مباشرة أو شحنًا مجانيًا، وهو ما يمكن أن يوفر عليك مبالغ ملحوظة على المدى الطويل." },
        { h: "قارن الأسعار بين المتاجر" },
        { p: "لا تفترض أن أول متجر تراه يقدم أفضل سعر. خصص بضع دقائق للمقارنة بين متجرين أو ثلاثة قبل الشراء، خاصة للمنتجات ذات القيمة العالية مثل الإلكترونيات." },
        { h: "اشترك في نشرة أسعار متجرك المفضل" },
        { p: "العديد من المتاجر ترسل عروضًا حصرية لمشتركي القائمة البريدية فقط. إذا كنت تتسوق بانتظام من متجر معين، فالاشتراك يستحق العناء." },
        { h: "استفد من مواسم التخفيضات" },
        { p: "خطط لمشترياتك الكبيرة حول مواسم التخفيضات الموسمية إن أمكن، حيث تكون الخصومات في أعلى مستوياتها خلال هذه الفترات." },
      ],
      en: [
        { h: "Always start by searching for a coupon code" },
        { p: "Before completing any purchase, take a minute to search for a valid coupon code for the store you're shopping at. These codes often provide a direct discount or free shipping, which can add up to significant savings over time." },
        { h: "Compare prices across stores" },
        { p: "Don't assume the first store you see has the best price. Spend a few minutes comparing two or three stores before buying, especially for higher-value items like electronics." },
        { h: "Subscribe to your favorite store's newsletter" },
        { p: "Many stores send exclusive offers only to email subscribers. If you shop regularly from a particular store, subscribing is worth it." },
        { h: "Time your purchases around sale seasons" },
        { p: "Plan bigger purchases around seasonal sale periods when possible, since discounts tend to be at their highest during these windows." },
      ],
    } },
  { id: "b2", slug: "verified-coupons-vs-unverified",
    category: "digital-services", author: "فريق التحرير", authorEn: "Editorial Team",
    date: "2026-08-10", readingTime: { ar: "4 دقائق", en: "4 min read" },
    image: "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1200&q=80",
    title: { ar: "ما الفرق بين الكوبون الموثّق وغير الموثّق؟",
             en: "What's the Difference Between a Verified and Unverified Coupon?" },
    excerpt: { ar: "دليل سريع لفهم كيف يتم التحقق من صلاحية أكواد الخصم ولماذا يهم ذلك عند التسوق.",
               en: "A quick guide to how coupon codes get verified, and why it matters when you shop." },
    relatedStores: ["iherb"], relatedCoupons: ["c1"],
    content: {
      ar: [
        { h: "كيف يتم التحقق من الكوبونات؟" },
        { p: "يقوم فريقنا بمراجعة أكواد الخصم بشكل دوري عبر اختبارها فعليًا في سلة الشراء لدى المتجر، والتأكد من أنها لا تزال تعمل قبل وضع علامة «تم التحقق» عليها." },
        { h: "لماذا قد يظهر كوبون غير موثق؟" },
        { p: "بعض الأكواد تُضاف حديثًا ولم تتم مراجعتها بعد، أو تعتمد على شروط خاصة يصعب اختبارها آليًا. هذا لا يعني بالضرورة أنها لا تعمل، لكن ننصح بالحذر واستخدام كوبون موثق كلما أمكن." },
        { h: "نصيحة عملية" },
        { p: "إذا لم يعمل الكود الذي اخترته، جرّب كودًا آخر من نفس المتجر أو تحقق من الشروط والأحكام الخاصة به." },
      ],
      en: [
        { h: "How are coupons verified?" },
        { p: "Our team periodically reviews discount codes by actually testing them at the store's checkout, confirming they still work before marking them as verified." },
        { h: "Why might a coupon appear unverified?" },
        { p: "Some codes are newly added and haven't been reviewed yet, or rely on special conditions that are hard to test automatically. That doesn't necessarily mean they don't work, but we recommend caution and using a verified coupon whenever possible." },
        { h: "A practical tip" },
        { p: "If the code you picked doesn't work, try another code from the same store or double-check its terms and conditions." },
      ],
    } },
  { id: "b3", slug: "best-time-to-book-flights",
    category: "travel", author: "فريق التحرير", authorEn: "Editorial Team",
    date: "2026-07-29", readingTime: { ar: "6 دقائق", en: "6 min read" },
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80",
    title: { ar: "متى تكون أفضل فرصة لحجز تذاكر الطيران بأرخص سعر؟",
             en: "When's the Best Time to Book Flights for the Cheapest Price?" },
    excerpt: { ar: "توقيت الحجز يؤثر مباشرة على السعر. إليك ما يجب معرفته قبل حجز رحلتك القادمة.",
               en: "Booking timing directly affects price. Here's what to know before booking your next flight." },
    relatedStores: ["booking"], relatedCoupons: ["c7"],
    content: {
      ar: [
        { h: "احجز مبكرًا لكن ليس مبكرًا جدًا" },
        { p: "غالبًا ما تكون الأسعار في أفضل حالاتها عند الحجز قبل 4 إلى 8 أسابيع من موعد السفر للرحلات الداخلية، وقبل 2 إلى 6 أشهر للرحلات الدولية." },
        { h: "راقب أيام منتصف الأسبوع" },
        { p: "الحجز والسفر في أيام الثلاثاء أو الأربعاء غالبًا ما يكون أرخص مقارنة بعطلة نهاية الأسبوع." },
        { h: "استخدم كوبونات الحجز الإضافية" },
        { p: "حتى بعد إيجاد أفضل سعر، تحقق دائمًا من وجود كود خصم إضافي على منصة الحجز التي تستخدمها لتوفير المزيد." },
      ],
      en: [
        { h: "Book early, but not too early" },
        { p: "Prices are often best when booking 4 to 8 weeks ahead for domestic flights, and 2 to 6 months ahead for international ones." },
        { h: "Watch midweek days" },
        { p: "Booking and flying on Tuesdays or Wednesdays is often cheaper compared to weekends." },
        { h: "Stack on a booking coupon" },
        { p: "Even after finding the best fare, always check whether the booking platform you're using has an extra discount code to save even more." },
      ],
    } },
];

// ---- Homepage stats (kept realistic, not exaggerated) ----
const SITE_STATS = {
  stores: STORES.length,
  coupons: COUPONS.length,
  categories: CATEGORIES.length,
};
